/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package my.example;


import my.example.hue.Lights;
import org.apache.avro.file.DataFileWriter;
import org.apache.avro.io.DatumWriter;
import org.apache.avro.specific.SpecificDatumWriter;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.File;
import java.io.IOException;
import java.util.Random;

import static my.example.utils.LightsGenerator.makeLights;


public class App {
    private static final Logger log = LoggerFactory.getLogger(App.class);
    public static void main(String[] args) throws IOException {
        Random random = new Random();
        var numLights = random.nextInt(5);
        var lights = makeLights(numLights);
        log.debug("Made {} lights.", lights.getLights().size());
        log.info("{}", lights);

        DatumWriter<Lights> lightsDatumWriter = new SpecificDatumWriter<>(Lights.class);
        try (DataFileWriter<Lights> dataFileWriter = new DataFileWriter<>(lightsDatumWriter)) {
            dataFileWriter.create(lights.getSchema(), new File("lights.avro"));
            dataFileWriter.append(lights);
        }
    }


}
