/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package my.example;

import my.example.hue.Lights;
import my.example.hue.Light;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;


import static my.example.utils.LightsGenerator.makeLight;


public class App {

    public static void main(String[] args) {
        Random random = new Random();

        var numLights = random.nextInt(5);
        List<Light> lightsList = new ArrayList<>(numLights);
        for (int idx = 0; idx <= numLights; idx++) {
            lightsList.add(makeLight(idx+1));
        }

        var lights = Lights.newBuilder().setLights(lightsList).build();
        System.out.println(lights);
    }


}
